name: Openwrt Build Bot
on:
  push:
    branches: master

jobs:
  buildpkg:
    name: Build Openwrt Package
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        SDK_URL:
        - https://downloads.openwrt.org/releases/21.02.0/targets/ramips/mt7621/openwrt-sdk-21.02.0-ramips-mt7621_gcc-8.4.0_musl.Linux-x86_64.tar.xz
    steps:
    - uses: actions/checkout@master
    - name: Env for Openwrt SDK
      run: sudo apt install -y libev-dev libc-ares-dev libudns-dev libncurses-dev
    - name: Download Openwrt SDK
      env:
        SDK_URL: ${{ matrix.SDK_URL }}
      run: |
        SDK_HOME=$(head -c -8 <<< $(basename $SDK_URL))
        wget $SDK_URL
        tar xf $(basename $SDK_URL) -C ~/
        mv ~/$SDK_HOME ~/sdk
        cp key-build ~/sdk/
    - name: Download Packages
      run: |
        cd ~/sdk
        # 添加包含 passwall 的 feed
        echo "src-git passwall https://github.com/xiaorouji/openwrt-passwall" >> feeds.conf.default
        # 因为部分软件包需要用到 upx，而官方 SDK 镜像中没有包含，所以自行安装
        sudo apt-get update
        sudo apt-get install upx -y
        cp /usr/bin/upx staging_dir/host/bin
        cp /usr/bin/upx-ucl staging_dir/host/bin
        # 更新所有 feeds
        ./scripts/feeds update -a
        # 这里因为 Xray 使用的 golang 版本较新而 SDK 中依赖的 golang 版本较旧，所以替换了旧的，用了 21.02 的 golang 配置
        pushd feeds/packages/lang
        rm -rf golang && svn co https://github.com/openwrt/packages/branches/openwrt-21.02/lang/golang
        popd
        ./scripts/feeds install v2ray-core v2ray-plugin trojan trojan-plus trojan-go luci-app-passwall
    - name: Compile
      run: |
        cd ~/sdk
        make defconfig
        # Edit config
        make
        # make package/luci-app-passwall/{clean,compile} -j4
        # 生成 index 和签名
        # make package/index
    - uses: actions/upload-artifact@v2
      with:
        name: ac2100-passwall
        path: ~/sdk/bin/packages
